### ISSUE TITLE
Mixin Definition: style not found

### ISSUE THREAD

**Issue by appreciated** [KaesDingeling/Hybrid-Menu#1]
There seems to be serveral issues with the current project setup.
I have pushed several changes to my fork and would like to contribute them:

- since the project does not rely on any GWT components I removed the widgetset. 
- a .gitignore was added and several eclipse project files were removed (these files should not be pushed to the github repository). I also removed the target folder. 
- updated the POM to match the current Vaadin Addon. 
- changed the path of the css file to make it includable
- transformed the css file into a scss file 
- updated the readme

**Comment by KaesDingeling** [comment]
Thanks,

but now I have the problem that I can not compile the WidgetSet anymore

[INFO] Scanning for projects...
[INFO]                                                                         
[INFO] ------------------------------------------------------------------------
[INFO] Building HybridMenu Add-on Demo 0.0.1.5-ALPHA
[INFO] ------------------------------------------------------------------------
[INFO] 
[INFO] --- vaadin-maven-plugin:8.0.6:update-widgetset (default-cli) @ hybridmenu-demo ---
[WARNING] GWT plugin is configured to detect modules, but none were found.
[INFO] No widgetsets found - generating AppWidgetset if necessary.
[INFO] Updating widgetset AppWidgetset
[INFO] Adding resource directory to command classpath: /home/max/git/Hybrid-Menu/HybridMenu-demo/src/main/resources
[INFO] Adding resource directory to command classpath: /home/max/git/Hybrid-Menu/HybridMenu-demo/target/generated-resources/gwt
[INFO] Widgetsets found from classpath:
[INFO] 	com.vaadin.DefaultWidgetSet in jar:file:/home/max/.m2/repository/com/vaadin/vaadin-client/8.0.6/vaadin-client-8.0.6.jar!/
[INFO] Addon styles found from classpath:
[INFO] 
[INFO] Search took 4ms
[INFO] 
[INFO] --- vaadin-maven-plugin:8.0.6:compile (default-cli) @ hybridmenu-demo ---
[WARNING] GWT plugin is configured to detect modules, but none were found.
[INFO] ------------------------------------------------------------------------
[INFO] BUILD SUCCESS
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 2.513 s
[INFO] Finished at: 2017-07-06T19:15:32+02:00
[INFO] Final Memory: 17M/348M
[INFO] ------------------------------------------------------------------------

**Comment by appreciated** [comment]
You simply don't need a widgetset from my perspective. You can simply you can simply use [fetch](https://vaadin.com/blog/-/blogs/demystifying-widget-set-cloud-compilation) -> which downloads the precompiled vaadin widgetset.

**Comment by appreciated** [comment]
Due to the warning i might have missed a configuration file, let me take a look into it.

**Comment by appreciated** [comment]
Fixed it with another pull request!

**Comment by KaesDingeling** [comment]
The widgetset compiler cannot found the addon

[INFO] Scanning for projects...
[INFO]                                                                         
[INFO] ------------------------------------------------------------------------
[INFO] Building HybridMenu Add-on Demo 0.0.1.5-ALPHA
[INFO] ------------------------------------------------------------------------
[INFO] 
[INFO] --- vaadin-maven-plugin:8.0.6:update-widgetset (default-cli) @ hybridmenu-demo ---
Widgetsets found from classpath:
	com.vaadin.DefaultWidgetSet in file:/home/max/.m2/repository/com/vaadin/vaadin-client/8.0.6/vaadin-client-8.0.6.jar

Search took 18ms
[INFO] 0 addons found.
log4j:WARN No appenders could be found for logger (org.jboss.resteasy.plugins.providers.DocumentProvider).
log4j:WARN Please initialize the log4j system properly.
[INFO] Widgetset config created to /home/max/git/Hybrid-Menu/HybridMenu-demo/target/generated-sources/wscdn/AppWidgetset.java. Public URL: null
[INFO] 
[INFO] --- vaadin-maven-plugin:8.0.6:compile (default-cli) @ hybridmenu-demo ---
Widgetsets found from classpath:
	com.vaadin.DefaultWidgetSet in file:/home/max/.m2/repository/com/vaadin/vaadin-client/8.0.6/vaadin-client-8.0.6.jar

Search took 13ms
[INFO] 0 addons found.
[INFO] No changes in widgetset: {style=OBF, vaadinVersion=8.0.6, eager=[], addons=[]}
[INFO] ------------------------------------------------------------------------
[INFO] BUILD SUCCESS
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 2.579 s
[INFO] Finished at: 2017-07-06T19:53:40+02:00
[INFO] Final Memory: 23M/205M
[INFO] ------------------------------------------------------------------------

**Comment by appreciated** [comment]
This should be no problem since your project does not contain any components that rely on GWT Librarys (Please correct me if I'm mistaken here) so you won't need any Widgetset compilation. 
Instead the user can simply take a precompiled widgetset. 

The only things the User needs is the Java Part and the SCSS.

**Comment by appreciated** [comment]
I currently got two addons in the "Vaadin Directory" ([Material Theme](https://vaadin.com/directory#!addon/material) and [Circular Progressbar](https://vaadin.com/directory#!addon/circular-progressbar-add-on1)) neither of them contains a Widgetset definition.

**Comment by KaesDingeling** [comment]
It is working. I would however not the CSS characteristics of the widget in the demo. In the previous version I had nothing to adjust. I wanted to try the following:

@import "../hybrid-menu/hybrid-menu.scss";

.demo {
	@include hybrid-menu;
}

When compiling the CSS, the following error is encountered:

[ERROR] Jul 06, 2017 8:39:15 PM com.vaadin.sass.internal.handler.SCSSErrorHandler severe
[ERROR] SCHWERWIEGEND: Import '../hybrid-menu/hybrid-menu.scss' in '/home/max/git/Hybrid-Menu/HybridMenu-demo/src/main/webapp/VAADIN/themes/demo/styles.scss' could not be found
[ERROR] Compiling theme "VAADIN/themes/demo" failed

**Comment by appreciated** [comment]
Another pull request should do the trick

**Comment by KaesDingeling** [comment]
Unfortunately, the error persists

**Comment by appreciated** [comment]
Have you tried putting it at the Vaadin directory? 
I think the vaadin-maven-plugin does resolve artefacts from the directory differently than plain maven dependencies.

**Comment by en3rgy97** [comment]
If you put this in the other Directory its Working.
How this path's Work ? 
@import "../hybrid-menu/hybrid-menu.scss";

When i change it to this: 
@import "../../../../../../../HybridMenu-addon/src/main/webapp/VAADIN/addons/hybrid-menu/hybrid-menu.scss";

Its Working.

**Comment by appreciated** [comment]
Try to release it to the Vaadin Directory and including it from there the paths should be added automatically.

**Comment by KaesDingeling** [comment]
The problem still exists

**Comment by appreciated** [comment]
Cannot confirm, it works for me.
I just created a new Project from the scratch, added the dependency 
````
<dependency>
   <groupId>org.vaadin.addons</groupId>
   <artifactId>hybridmenu</artifactId>
   <version>0.0.1.4-ALPHA</version>
</dependency>
````
and ran `clean install`.

My addons.scss
````
/* This file is automatically managed and will be overwritten from time to time. */
/* Do not manually edit this file. */

/* Provided by hybridmenu-0.0.1.4-ALPHA.jar */
@import "../../../VAADIN/addons/hybrid-menu/hybrid-menu.scss";

/* Import and include this mixin into your project theme to include the addon themes */
@mixin addons {
	@include hybrid-menu;
}
````

Seems fine to me

**Comment by KaesDingeling** [comment]
Ok, but thank you very much :)

**Comment by appreciated** [comment]
I just try to help ;-). If there is still a problem let me know. 

try to purge the local repository by deleting the maven folder `c:\Users\username\.m2\repository`. And running another `clean install`.

**Comment by KaesDingeling** [comment]
If I load the addon from the Vaadin repository and the widgetset compile I still get an error (external project since the demo application is now)

[INFO] Scanning for projects...
[INFO]                                                                         
[INFO] ------------------------------------------------------------------------
[INFO] Building myapplication 1.0-SNAPSHOT
[INFO] ------------------------------------------------------------------------
[INFO] 
[INFO] --- vaadin-maven-plugin:8.0.6:update-widgetset (default-cli) @ myapplication ---
[WARNING] GWT plugin is configured to detect modules, but none were found.
[INFO] No widgetsets found - generating AppWidgetset if necessary.
[INFO] Updating widgetset AppWidgetset
[INFO] Adding resource directory to command classpath: /home/max/workspace/myapplication/src/main/resources
[INFO] Adding resource directory to command classpath: /home/max/workspace/myapplication/target/generated-resources/gwt
[INFO] Using com.vaadin:vaadin-client version 8.0.6
[INFO] Using com.vaadin:vaadin-client-compiler version 8.0.6
[INFO] Widgetsets found from classpath:
[INFO] 	kaesdingeling.hybridmenu.WidgetSet in jar:file:/home/max/.m2/repository/org/vaadin/addons/hybridmenu/0.0.1.4-ALPHA/hybridmenu-0.0.1.4-ALPHA.jar!/
[INFO] 	com.vaadin.DefaultWidgetSet in jar:file:/home/max/.m2/repository/com/vaadin/vaadin-client/8.0.6/vaadin-client-8.0.6.jar!/
[INFO] Addon styles found from classpath:
[INFO] 	VAADIN/addons/HybridMenu/style.scss in jar:file:/home/max/.m2/repository/org/vaadin/addons/hybridmenu/0.0.1.4-ALPHA/hybridmenu-0.0.1.4-ALPHA.jar!/
[INFO] 
[INFO] Search took 4ms
[INFO] 
[INFO] --- vaadin-maven-plugin:8.0.6:compile (default-cli) @ myapplication ---
[INFO] auto discovered modules [AppWidgetset]
[INFO] Using com.vaadin:vaadin-client version 8.0.6
[INFO] Using com.vaadin:vaadin-client-compiler version 8.0.6
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 2.160 s
[INFO] Finished at: 2017-07-07T10:09:19+02:00
[INFO] Final Memory: 15M/245M
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal com.vaadin:vaadin-maven-plugin:8.0.6:compile (default-cli) on project myapplication: GWT Module kaesdingeling.hybridmenu.WidgetSet not found in project sources or resources. -> [Help 1]
[ERROR] 
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoExecutionException

**Comment by appreciated** [comment]
Would you mind giving me your test project, so I can have a look?

**Comment by KaesDingeling** [comment]
Was probably an error in my example project. Now everything works perfectly. Here is my test project.

https://github.com/KaesDingeling/Hybrid-Menu-Test

Thanks again :)

**Comment by KaesDingeling** [comment]
If I create a Vaadinprojekt on another machine and then add my addon, it is already in the pom.xml already errors.
Unfortunately, I can not go any further.

**Comment by appreciated** [comment]
[The File "MANIFEST.MF" you pushed with the second last commit "500faae5f....."](https://github.com/KaesDingeling/Hybrid-Menu/blob/500faae5fdc8f9d817625fc691d53bce7f6aa6bc/HybridMenu-addon/bin/src/main/java/META-INF/MANIFEST.MF) overrides the path of the scss file that was set in the POM.

This causes an invalid Path to be included when adding the addon as dependency.  

**addons.scss**
````
/* This file is automatically managed and will be overwritten from time to time. */
/* Do not manually edit this file. */

/* Provided by hybridmenu-0.0.1.4-ALPHA.jar */
@import "../../../VAADIN/addons/HybridMenu/style.scss";

/* Import and include this mixin into your project theme to include the addon themes */
@mixin addons {
	@include style;
}
````


[One commit later in the ALPHA-6 however you corrected the path again](https://github.com/KaesDingeling/Hybrid-Menu/blob/master/HybridMenu-addon/src/main/java/META-INF/MANIFEST.MF). If you update the addon to the current sources it should be working again.

**Comment by KaesDingeling** [comment]
I do not understand this with the manifest file, if I omit the file in java/META-INF/ I can not export the widget. Have now the actual code uploaded but still the same error.

http://i.imgur.com/gXtZzJ6.png

**Comment by KaesDingeling** [comment]
I had the entry from the pom.xml removed, since I want to try any possible for me somehow logical sounds, but still does not.

http://i.imgur.com/tiFGXEF.png

**Comment by appreciated** [comment]
The export plugin of eclipse might have a bug? You can use Maven for this.  

Run a `install` goal and take a look at your target folder of the addon module, you should find a zip file 
 which you can upload straight to the vaadin directory.

**Comment by KaesDingeling** [comment]
Perfect, that solved the problem. Finally, thank you for helping me.
